#!/usr/bin/env bash
# OpenClaw sandbox — staged setup. Run stages in order:
#   bash setup.sh env      # generate .env (gateway token + z.ai key from ANTHROPIC_AUTH_TOKEN)
#   bash setup.sh pull     # pull gateway image, pin it by digest into .env
#   bash setup.sh egress   # build + start the allowlist proxy (infra only, not the agent)
#   bash setup.sh onboard  # headless onboarding (zai provider, token auth, no channels)
#   bash setup.sh config   # deep-merge hardened-config.json into openclaw.json
#   bash setup.sh audit    # OpenClaw static security audit
#   bash setup.sh verify   # escape-path verification tests (see SECURITY-REVIEW.md)
#
# GO-LIVE (operator decision, not part of setup):
#   docker compose up -d   # starts egress + gateway
#   Control UI: http://127.0.0.1:18789/  (paste gateway token from .env)
set -euo pipefail
cd "$(dirname "$0")"

stage="${1:-}"

case "$stage" in
  env)
    if [ -f .env ]; then echo ".env already exists — delete it first to regenerate"; exit 1; fi
    ZAI_KEY="${ANTHROPIC_AUTH_TOKEN:-${ZAI_API_KEY:-}}"
    if [ -z "$ZAI_KEY" ]; then
      echo "ERROR: no z.ai key found (set ANTHROPIC_AUTH_TOKEN or ZAI_API_KEY)"; exit 1
    fi
    GATEWAY_TOKEN="$(openssl rand -hex 32)"
    {
      echo "# generated by setup.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — NEVER COMMIT (.gitignore'd)"
      echo "OPENCLAW_IMAGE=ghcr.io/openclaw/openclaw:latest"
      echo "OPENCLAW_GATEWAY_TOKEN=${GATEWAY_TOKEN}"
      echo "ZAI_API_KEY=${ZAI_KEY}"
      echo "OPENCLAW_GATEWAY_PORT=18789"
      echo "OPENCLAW_TZ=UTC"
    } > .env
    chmod 600 .env
    echo "[env] .env written (token: ${#GATEWAY_TOKEN} chars hex, z.ai key: ${#ZAI_KEY} chars)"
    ;;

  pull)
    source .env 2>/dev/null || { echo "run 'bash setup.sh env' first"; exit 1; }
    docker pull ghcr.io/openclaw/openclaw:latest
    DIGEST="$(docker inspect --format '{{index .RepoDigests 0}}' ghcr.io/openclaw/openclaw:latest)"
    # pin by digest (supply-chain hardening: image content can never silently drift)
    sed -i.bak "s|^OPENCLAW_IMAGE=.*|OPENCLAW_IMAGE=${DIGEST}|" .env && rm -f .env.bak
    echo "[pull] pinned OPENCLAW_IMAGE=${DIGEST}"
    ;;

  egress)
    docker compose build egress
    docker compose up -d egress
    sleep 2
    docker compose ps egress
    echo "[egress] proxy up — allowlist: .z.ai .bigmodel.cn (443 CONNECT only)"
    ;;

  egress-setup)
    # WIDEN allowlist for a scripted operator step (agent must not be running).
    printf '# TEMPORARILY WIDENED by setup.sh %s — run egress-lockdown when done\nregistry.npmjs.org\n' "$(date -u +%FT%TZ)" > egress/extra-domains.txt
    docker compose up -d --force-recreate egress
    echo "[egress-setup] allowlist WIDENED: registry.npmjs.org (operator steps only)"
    ;;

  egress-lockdown)
    printf '# Widened allowlist — ships EMPTY (agent must never have npm egress).\n# `bash setup.sh egress-setup` writes registry.npmjs.org here for scripted\n# operator steps; `bash setup.sh egress-lockdown` empties it again.\n' > egress/extra-domains.txt
    docker compose up -d --force-recreate egress
    echo "[egress-lockdown] allowlist back to strict: .z.ai .bigmodel.cn only"
    ;;

  onboard)
    # npm egress needed once for the official zai provider plugin — widened
    # for this step only, then snapped back (trap guarantees lockdown).
    bash "$0" egress-setup
    trap 'bash "$0" egress-lockdown' EXIT
    docker compose run -T --rm --entrypoint node openclaw-gateway \
      dist/index.js onboard \
      --non-interactive --accept-risk --skip-health \
      --mode local \
      --auth-choice zai-coding-global \
      --secret-input-mode ref \
      --gateway-auth token --gateway-token-ref-env OPENCLAW_GATEWAY_TOKEN \
      --skip-channels --no-install-daemon
    ;;

  config)
    MERGE_JS="$(cat scripts/merge-config.js)"
    docker compose run -T --rm --no-deps --entrypoint node openclaw-gateway \
      -e "$MERGE_JS" < hardened-config.json
    ;;

  audit)
    docker compose run -T --rm --no-deps --entrypoint node openclaw-gateway \
      dist/index.js security audit
    ;;

  verify)
    bash verify-sandbox.sh
    ;;

  *)
    grep -E '^  [a-z]+\)' "$0" | sed 's/) # / — /;s/)//'
    echo "Usage: bash setup.sh <env|pull|egress|onboard|config|audit|verify>"
    ;;
esac
